# リポジトリのコードをチェックアウト
- name: Checkout repository
  uses: actions/checkout@v3

# 現在の作業ディレクトリを確認
- name: Check current directory
  run: |
    pwd
    ls -l

# extracted_filesディレクトリが存在しない場合に作成
- name: Create extracted_files directory if it doesn't exist
  run: |
    mkdir -p extracted_files

# ZIPファイルを解凍する
- name: Extract ZIP file
  run: |
    unzip browser_20241211_22126.zip -d extracted_files
